version: "3.8"
services:
  webapp:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: next-js-typescript
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    networks:
      - next-network
    environment:
      MONGODB_URI: mongodb://mongo:27017/test

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dbTest
    ports:
      - "27017:27017"
    networks:
      - next-network

  dbSeeder:
    image: node:lts-alpine
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: next-db-seeder
    restart: on-failure
    volumes:
      - ./mongo/:/dbSeeder
    networks:
      - next-network

networks:
  next-network:
    driver: bridge

volumes:
  data-volume:
